### ISSUE TITLE
Improvement: make capability for the responsibility for time slots

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#10]
Hi,

it's me agein. :)

First, I'll explain the situation in our Moodle system that leads to this request: 
We've got several standard roles like student and editing teacher. Additionally we have supporting roles that have almost the same rights as an editing teacher to be able to access and test things in a course that needs support. Those supporting roles, of course, got the capability mod/organizer:addslots to be able to add slots to the organizer.

Unfortunately those roles also appear in the teacher list because you use the function get_users_by_capability($context, 'mod/organizer:addslots'); to get the users of the list. 
This is irritating for our teachers when people appear in this list who are not intended to be listed there.

So it would be great if you could separate the capabilities to be able to add slots and to be responsible for slots. The teachers list could be created by getting the users who have the right to be responsible for slots and so other user still could add slots without appearing in this list.

Kind regards
Kathrin

**Comment by mkemmerling** [comment]
Hi Kathrin,

we added your request to our backlog to let the product owners decide whether to implement this feature or not. My personal impression is that this is a rather a 'luxury' problem. I suppose in general teachers know whom to select from them list.

Kind regards,
Markus Kemmerling

**Comment by abias** [comment]
Hi Markus,

thanks for your feedback. I agree that for your use cases, this dual usage of the capability might be a luxury problem, but in our scenario which Kathrin described it's at least annoying. Of course, teachers will know who to select from the list, but they are not prepared to see support staff in this list.

I dare to say that this is a 10 line patch to create a backwards compatible solution. If we create a pull request here in Github, will you accept it into the plugin?

Thanks,
Alex

**Comment by mkemmerling** [comment]
Hi Alex,

its not up to me to decide this, but I added a comment in our backlog. It would certainly help, but probably still not be an issue with high priority. I'll keep you informed about the product owner's decision.

Maybe the university of Ulm should consider to join the AMC ;-)

Cheers,
Markus

**Comment by kaspot** [comment]
Hi Alex, 
if you would create a pull request, than it would be much easier for us to decide if we could include it into our plugin and it would increase the probability of including your feature request into our code ;-)

Cheers Kasia

**Comment by abias** [comment]
Hi,

I see that you have integrated this patch in commit d588e1a and would therefore ask you to close this ticket.

Thanks,
Alex
