### ISSUE TITLE
multiple students only with gropus

### ISSUE THREAD

**Issue by lvittori** [academic-moodle-cooperation/moodle-mod_organizer#100]
Hello,

it seems the new version allows mutliple students per time slots only with groups (I knoow they can be generated, but the groups will change constantly and so the groups-section will be flooded). it would be nice if the old behaviour (allowing multiple students without creating a group) will be available again. 

Regards

**Comment by bluetom** [comment]
Hi,
if the organizer is not in group mode as many as "max participants" defined in the slot settings are allowed to book a slot. Are you sure to have increased that number?
Regards,
Thomas

**Comment by goggo24** [comment]
If you use "group appointments" => "no group appointments" you can still work with single user registration. You can still decide how many students can book a slot, when you create the slots - there was no change in this workflow.
![grafik](https://user-images.githubusercontent.com/16721900/153136019-6935a666-2b6a-4e9f-a56c-bfe26eaae69e.png)

At the moment multiple registration is not implemented - neither for groups than for a single user. We have it on our roadmap for organizer 4.0.
