### ISSUE TITLE
unchecking weekday slot creates a new one

### ISSUE THREAD

**Issue by Urpokarhu1** [academic-moodle-cooperation/moodle-mod_organizer#107]
Hello,

There is a bug in organizer, everytime you uncheck weekdayday slot, it creates a new one. This is unnecessary and confusing for the users especially when you create just one appointment.

tested with Moodle 3.9.15 & mod_organizer v3.9.2 (2020082502)

https://user-images.githubusercontent.com/53904029/187402523-666ca116-3ec4-47bb-8332-c96336a82323.mp4

**Comment by goggo24** [comment]
Thanks for reporting. We will add it to our backlog.
