### ISSUE TITLE
double description

### ISSUE THREAD

**Issue by HWZElearning** [academic-moodle-cooperation/moodle-mod_organizer#110]
We are currently in the testing phase of Moodle 4.1 (Version 4.1 (Build: 20221128) (2022112800)). We have installed the "Scheduler" plugin (mod_organizer) and it is also updated to the latest version, v4.1.0 2022112800

Unfortunately it always shows the description twice.
Kind regards Gabriella

**Comment by goggo24** [comment]
Thanks for reporting. Bug will be fixed with the next minor version - coming soon.

**Comment by mkemmerling** [comment]
Fixed with version 4.1.1.
