### ISSUE TITLE
New activity icon

### ISSUE THREAD

**Issue by zabellemotte** [academic-moodle-cooperation/moodle-mod_organizer#111]
It would be great this wonderful plugin to have a new icon for good integration in Moodle 4 :
https://docs.moodle.org/dev/Moodle_4.0_developer_update#Activity_icons

**Comment by bluetom** [comment]
We will publish the new icon with the next (patch) version 4.1+

**Comment by stdoma** [comment]
Hi!
The new icon came with the current version. Thanks for the customization.

The icon has no background color or it cannot be set. This gives you a white icon on a white background.
Moodle: 4.1.4+ / Organizer 4.1.2
![organizer-Screenshot 2023-06-26 081210](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/92015860/41fc86fc-4e2a-4861-aed5-e8ed6bcf61f7)

If I disable the CSS rule for the background, the icon has a background color.
![organizer-Screenshot 2023-06-26 081311](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/92015860/dec0eda2-5620-402d-8c06-8ed75ad5e0b9)

**Comment by zabellemotte** [comment]
Works fine on my Moodle 4.12 local version without css customization.

**Comment by stdoma** [comment]
I was able to reproduce the problem.
I used the boost_union theme. In this you can change the colors of the activities. For all other activities, the setup of the color worked during installation.
After installation, the organizer has the selection "other" and not "administration", which stands for the respective colors from the first post.
After I changed the setting, the display is fine.

I'm assuming the default comes from the plugin's settings. Is the color code in the organizer different than one of the standard colors?

**Comment by bluetom** [comment]
Fixed in current organizer version 4.2.
