### ISSUE TITLE
v3.11.5 (2021062305) - registration status tab is broken

### ISSUE THREAD

**Issue by stdoma** [academic-moodle-cooperation/moodle-mod_organizer#112]
Hello!
Today the new version for Moodle 3.11 was released.
In this release, I can no longer open the enrollment status tab when the course has no students.

Error: Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays
![Screenshot 2023-03-01 164054](https://user-images.githubusercontent.com/92015860/222188670-72965869-b7a4-484d-a766-312b15e3e350.jpg)

**Comment by bluetom** [comment]
Thank you for the notification!
We will fix it and publish the fixed version as soon as possible.
