### ISSUE TITLE
Error message on "Registration status" tab on Moodle 4.1 when no student enrolled in course

### ISSUE THREAD

**Issue by zabellemotte** [academic-moodle-cooperation/moodle-mod_organizer#113]
I an testing your very interresting plugin on Moodle 4.1 and I encounter an error message while consulting the "Registration statuts" tab when no students are enrolled in the course:
Exception - Call to a member function valid() on array

**Comment by bluetom** [comment]
Thank you for reporting!
This issue was fixed for Organizer Version 3.11.5+.
We will fix it for 4.1+ as well soon...

**Comment by bluetom** [comment]
Fixed in the current organizer version 4.2 (as well).
