### ISSUE TITLE
Error while editing a slot on Moodle 4.1

### ISSUE THREAD

**Issue by zabellemotte** [academic-moodle-cooperation/moodle-mod_organizer#114]
While testing this plugin on Moodle 4.1, I encounter an error while editing a slot :
Exception - method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

**Comment by zabellemotte** [comment]
Here is the button I click ...
![button_printing_organizer](https://user-images.githubusercontent.com/38882780/227537352-f78bd769-8686-4822-903f-522130b4bf9f.png)

**Comment by zabellemotte** [comment]
And here is the full error message ...
![error_printing_organizer](https://user-images.githubusercontent.com/38882780/227537465-d28fd5d8-47cd-45ac-be31-b563e93d9da1.png)

**Comment by zabellemotte** [comment]
Here is the button I click ...
![modify_slot_organizer](https://user-images.githubusercontent.com/38882780/227540545-482355ff-d4a1-4310-9d88-237d00defb4e.png)

**Comment by zabellemotte** [comment]
Here is the full error message ...
![error_modifying_slot_organizer](https://user-images.githubusercontent.com/38882780/227542163-c29fb537-52dd-43db-8ebf-205132d44fdd.png)

**Comment by bluetom** [comment]
Closed.
