### ISSUE TITLE
Error while printing informations about a slot in Moodle 4.1

### ISSUE THREAD

**Issue by zabellemotte** [academic-moodle-cooperation/moodle-mod_organizer#115]
While testing this plugin on Moodle 4.1, I encounter an error message while trying to print a selected slot:
Error reading from database

Are there prerequisites for this functionnalilty to work ? 
If it is the case, please document it.

**Comment by bluetom** [comment]
Yes, there is a prerequisite, but there should be a message indicating the solution ("Single print slot user profile fields" should be defined in the instance settings).
Could you please take a screenshot of the page right before the error appears and one of the error message itself?
If it is possible for you please set the side administration option "debug" to "DEVELOPER:..." for the test. (<your_moodle_domainname>/admin/settings.php?section=debugging)

**Comment by zabellemotte** [comment]
Here is the printing button I click
![button_printing_organizer](https://user-images.githubusercontent.com/38882780/227538660-eb559042-8082-4b43-b33b-eac38c58b3da.png)

**Comment by bluetom** [comment]
This error occurs if you install a not Moodle 4 compatible organizer version [< v4.0.0 (2022102800)] on a Moodle 4 installation...
