### ISSUE TITLE
Slot cannot be graded (v4.1.1)

### ISSUE THREAD

**Issue by wiebkemueller-hsh** [academic-moodle-cooperation/moodle-mod_organizer#116]
When trying to grade a past slot or a slot in future, this error message is shown:
![grafik](https://user-images.githubusercontent.com/72548805/228516588-54b03196-efbf-4fed-859b-da8d3e65e7b9.png)

The grading dialog is not shown, the grading cannot be done and the students cannot be granted a new slot either.

We are using 
mod_organizer
version: 2022112801 (v4.1.1) 

running on 
Moodle 4.1.2 (Build: 20230313)
with Boost Union theme v4.1-r6

Thanks for looking into this or providing further advice. 

Wiebke (Hochschule Hannover)

**Comment by bluetom** [comment]
This version of organizer has been tested with this Moodle version in our new theme which is based on union boost. So it is no surprise that I can not reproduce the bug.
We would need further information.
If it is possible for you please change the "debug" option in the side administration to "DEVELOPER", repeat the test case and post here the new and than useful error message which will appear.

**Comment by wiebkemueller-hsh** [comment]
Hi Bluetom, the attached debug messages always appear:
- when trying to grade a slot that has been reserved by sb.
- when trying to grade a slot that has NOT YET been reserved by sb.
- past slots
- future slots

Thank you for further looking into this. Please give us a hint if you need further information/testing.

Wiebke
[mod_organizer.txt](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/files/11110409/mod_organizer.txt)

**Comment by bluetom** [comment]
Thank you for the error messages! Which php-Version is active at your Moodle server?

**Comment by wiebkemueller-hsh** [comment]
Hi Bluetom, it is php 8.1.17 on the test server I used.

**Comment by bluetom** [comment]
So this is in fact a matter of the php version. We tested with php 8.0 but this errors occur with php 8.1. We will bundle a fix version (4.1.2) for this issues together with a new Moodle4-compatible icon propably next week...

**Comment by wiebkemueller-hsh** [comment]
Dear @bluetom 

we really appreciate the new version (v3.11.7) of mod_organizer that you published, thank you for that! Regarding the bundle fix version 4.1.2 you mentioned above are there plans to work on this before the summer break and will it include the new features? I'm only asking since we'll have to update to Moodle 4.X in August and currently hesitate to upgrade beforehand to 3.11.7 to avoid having to pullback features with the Moodle Update to 4.1.

Thanks very much for your great work on this anyway!
Wiebke

**Comment by bluetom** [comment]
Dear Wiebke,

the "bad" news is: This organizer version is going to be discontinued by the end of the year 2023.

The **good** news is: A complete new organizer is being programmed at the moment! This new organizer will be prettier, more user-friendly and more powerful than the old one. We hope to have published it by summer 2023.

The "old" organizer version 3.11.8 with the multi-booking feature and with Moodle 4.2 compatibility will be published in June 2023.

Cheers,
Thomas
