### ISSUE TITLE
Improvement : make it possible to define a number of slot to book at a time

### ISSUE THREAD

**Issue by zabellemotte** [academic-moodle-cooperation/moodle-mod_organizer#117]
It seems an organizer only accepts one slot booking for each student.
It would be great to enable a booking of one slot at a time that enables a student to make a new slot booking after an appointment, for example in case of teacher duty period open each monday between 4 and 6.

**Comment by zabellemotte** [comment]
It seems once a student met the teacher, the teacher may authorize the student to book a new slot. 
It is an other way to solve this problem, but it is less practical.

**Comment by bluetom** [comment]
The organizer is developed totally new currently and this feature is part of it. Hopefully the new version (compatible with Moodle 4.x) will be available by the end of 2023.

**Comment by bluetom** [comment]
With the current organizer versions 4.2 and 3.11.7 the multibooking feature has been introduced. Now students can book more than one slot (in the usual way).
