### ISSUE TITLE
Improvement : when a teacher enables a student to book a new slot, all informations about the first appointment should not be lost

### ISSUE THREAD

**Issue by zabellemotte** [academic-moodle-cooperation/moodle-mod_organizer#118]
I noticed that when a student is enabled to have new appoitment, all informations about the preceeding apointment are lost. In case of teacher coaching meeting, there may be several slot booked in the same organizer activity, but one at a time. And the teacher wants to preserve informations about all appointments.

**Comment by bluetom** [comment]
The organizer is developped totally new currently and we will take your hints and proposals into account. Hopefully the new version will be available by the end of 2023.

**Comment by bluetom** [comment]
With the current organizer versions 4.2 and 3.11.7 the multibooking feature has been introduced. Now students can book more than one slot (in the usual way).
