### ISSUE TITLE
Bug in slots_eval.php @ v3.11.7 (2021062307)

### ISSUE THREAD

**Issue by NeverGitUp** [academic-moodle-cooperation/moodle-mod_organizer#119]
There is a bug in slots_eval.php lin 38

$slots = $slots = optional_param_array('slots', [], PARAM_INT);

I replaced it with the line in the previous version (2020120101):
$slots = organizer_get_param_slots();

Then it works as expected. 

I found it in the file locallib.php as well (line 2065), framed with the warning "// Dirty, dirty hack..."
The previous version locallib.php ends at line 1991.

So maybe you are going to check that and release an upgraded version.

Thank you.

**Comment by bluetom** [comment]
This bug is fixed in the new organizer version 4.2 which has been published yesterday: [Link to moodle.org](https://moodle.org/plugins/mod_organizer).
It is tested and runs also with Moodle 3.11, but you have to manipulate the "requires"-parameter in version.php to get it upgraded.

**Comment by bluetom** [comment]
Fixed in stable Moodle branches 4.x and 3.11.7
