### ISSUE TITLE
Unsupported $module syntax detected in version.php of the mod_organizer plugin.

### ISSUE THREAD

**Issue by nitro2010** [academic-moodle-cooperation/moodle-mod_organizer#12]
Hello,

Please update your plugin for Moodle v3.0

While installating I get errors [all text with debugging option on]:

Unsupported $module syntax detected in version.php of the mod_organizer plugin.
line 322 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin mod_organizer does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

**Comment by mkemmerling** [comment]
Hi,
we already fixed the outdated `$module` syntax, but somehow it didn't make it into the GitHub repository. I will look after this. But that doesn't mean that the plugin will work for Moodle 3.0. We are currently updating the plugin for Moodle 2.9 and afterwards for Moodle 3.0. Generally, we intend to get closer with our plugin releases to Moodle releases, but we are not there yet.

**Comment by mkemmerling** [comment]
`$module` has now been replaced by `$plugin`in version.php of the master and MOODLE_28_STABLE branches.
