### ISSUE TITLE
Managers should not have leadslots permission by default

### ISSUE THREAD

**Issue by zabellemotte** [academic-moodle-cooperation/moodle-mod_organizer#120]
While deploying Organizer on several Moodle, we noticed that by default, the manager role has this capability
mod/organizer:leadslots
and they appear in the list of persons that may be have a meeting with students.
This is not legitimate.
The managers are persons that may step in courses to help teachers to configure theirs activities, but they are not the main contact with students.

**Comment by bluetom** [comment]
This is fixed in the new version 4.2.2, which has been published today: https://moodle.org/plugins/mod_organizer/versions
