### ISSUE TITLE
(Bug?): missing settings in version 4.1.2

### ISSUE THREAD

**Issue by stdoma** [academic-moodle-cooperation/moodle-mod_organizer#121]
In the current version for Moodle 4.1, individual settings are missing in the plugin (v4.1.2 (2022112802)).
You cannot set the settings for the minimum and maximum bookings. This means you can only book one item in a organizer.
I didn't find any fields in the database that would allow the setting.

Settings in an old plugin version for Moodle 3:
![v3](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/92015860/d962de91-fee3-4bf3-8d22-ca486311ebdd)

Settings in the current plugin version for Moodle 4.1:
![v4](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/92015860/9e154071-3520-4744-98f7-1245746d2d86)

**Comment by bluetom** [comment]
The version 4.1+ is not a version which supports the multibooking feature.
If you want to use this organizer feature with Moodle 4.1 we recommend to install the organizer version 4.2 and change the "requires" parameter in version.php to Moodle 4.1. There should be no problem.

**Comment by mrkskwsnck** [comment]
I've created the PR https://github.com/academic-moodle-cooperation/moodle-mod_organizer/pull/128 to address this very issue
