### ISSUE TITLE
BUG (v4.2.1 (2023053101)): Incorrect text when creating appointments

### ISSUE THREAD

**Issue by stdoma** [academic-moodle-cooperation/moodle-mod_organizer#122]
If you generate a single appointment, you will see the information text from the message_warning_no_slots_added variable.  The appointment is regularly recorded in the database.
As far as I can see, one of these variables would have to be selected in this case: message_info_slots_added_pl , message_info_slots_added_sg
![Screenshot 2023-09-20 134234](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/92015860/a9727af3-fe0d-4494-9fb4-f7e03c628a14)

**Comment by bluetom** [comment]
This is fixed in the new version 4.2.2, which has been published today: https://moodle.org/plugins/mod_organizer/versions
