### ISSUE TITLE
Bug for group enrolment when non students roles are enrolled in groups

### ISSUE THREAD

**Issue by zabellemotte** [academic-moodle-cooperation/moodle-mod_organizer#123]
The organizer groups enrolment forces students to be in one group, and that is an important control especially when grades are assigned to the appointment.

But we had a difficulty in one course where tutors are enrolled in groups with non editing teacher role.
Tutors are enrolled in several groups and this makes the organizer activity fail and this could also raise problems when a grade is given.

I think the verification that each member of the grouping is only in one group should only concern the student role. And the grades should only be assigned to students. While email notifications may be adressed to all members of the groupe, tutors included.

Note that we found a temporary workaround : we created a second grouping with exactly the same members without the tutors. But it is not easy to implement and to manage groups changes in such situation.

**Comment by zabellemotte** [comment]
I had a look at the code to find where to have modifications to correct that bug.

I found at least 3 functions extractig group members.

In locallib.php, function organizer_add_event_slot calls a groups_get_members generic function to load the enrolled users for a group appointment. I think this function does not need to be modified because tutors mays have this information. The same function is called in the send_reminder.php file and fore the same reason tutors do not have to be excluded of mail notifications sending.

In mod_form.php, the _get_membership private function extracts all members of one of the group in the grouping. This function is called in the validation function in the same file that verifies if each member is only in one groupe. I think the _get_membership function should be modified to select only users with student role (or with a role that has a specific permission).

Finally, in the grading system, the non student users should be excluded. And this could arise while modifying the lib.php file, function organizer_update_all_grades. Il this function, the generic function get_enrolled_users should hopefully be called with a specific permission restriction as it may be readed here :
https://moodledev.io/docs/apis/subsystems/enrol#get_enrolled_users
and the query should be adapted to exclude the non student role.

I think it should be sufficient to solve the problem but I am not fully sure, so I prefer the lead developpers to lead the changes, but I am reday to test.

With great thanks for this magical plugin for group appointments.

Kisses

Zabelle

**Comment by zabellemotte** [comment]
I had a look at the Moodle permissions to find an intelligent way to define roles to be excluded of the organizer validation and grading system.
It may be a good idea to exclude all roles that have the permission moodle/grade:viewall.

**Comment by bluetom** [comment]
Of course, you should not be able to grade roles which are not defined to be graded. I'm working on a new organizer minor version (4.2.3) ought to be published during the next two weeks. I will fix this problem in this version. 

At our university it is not allowed to have the same person as student and tutor(=teacher) in the same course. It is allowed at your site?

**Comment by zabellemotte** [comment]
Thanks for following @bluetom.
In our university, it arises quite often that students following the latest years of a course program are implied in the first year courses. They do not have student ant tutor role in a course. They have a tutor role in some courses and student role in others. And enrolling them as tutors in the groups they supervise with non editing teacher role, make it possible for them to access all production of theirs groups, without having access to other groupes productions.

**Comment by bluetom** [comment]
The new organizer version 4.2.3 contains fixes for these problems: https://moodle.org/plugins/mod_organizer/versions

**Comment by zabellemotte** [comment]
Great thaks for this evolution @bluetom ! I will relate this good news to our professors !

**Comment by zabellemotte** [comment]
I have been testing the latest version (4.3.1) of organizer and I am very happy to note this issue is solved. Great thanks @bluetom.
