### ISSUE TITLE
feature request: option to hide students that don't have access to the course

### ISSUE THREAD

**Issue by Urpokarhu1** [academic-moodle-cooperation/moodle-mod_organizer#124]
Hello,
I would like to see an option in settings to hide students that don't have access to the course anymore (f.ex. when their registration have expired)

![image](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/53904029/925a75c4-eb6f-43d6-89e6-a14135aee3c5)
![image](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/53904029/3942d995-09c5-47dc-83e7-479d52d115d1)

**Comment by bluetom** [comment]
Oh yes, that would be reasonable! I'm working on a new organizer minor version (4.2.3) ought to be published during the next two weeks. I will fix this problem in this version.

**Comment by bluetom** [comment]
The new organizer version 4.2.3 contains a fix for this problem: https://moodle.org/plugins/mod_organizer/versions

**Comment by Urpokarhu1** [comment]
Hello,
Thanks, can you concider releasing this for Moodle version 4.1 also? It is a long term support Moodle.

**Comment by bluetom** [comment]
Hello,
just change the $plugin->requires property in the version.php of the plugin to your Moodle version. This plugin version should also run under Moodle 4.1.x!

**Comment by Urpokarhu1** [comment]
Hello,
Please release this fix for https://moodle.org/plugins/mod_organizer we host multiple Moodle sites so this is crucial for us.

**Comment by bluetom** [comment]
What is the problem?

**Comment by Urpokarhu1** [comment]
We are hosting multiple Moodle installations and our automatic package manager uses the version number found on https://moodle.org/plugins/mod_organizer so if there isn't a 4.1 version available with this fix we cannot add it to package manager and install it to all our installations.

**Comment by bluetom** [comment]
This feature has been backported to version 4.1.
