### ISSUE TITLE
Teacher must be able to delete a registration

### ISSUE THREAD

**Issue by zabellemotte** [academic-moodle-cooperation/moodle-mod_organizer#129]
For the moment, when a teacher wants to modify one student registration, he has to grade the registration and to allow a new registration. But this encodes also the student attendance, even if the meeting is planned in the future. And it is not an easy way to manage registration changes.

It would be easier to make it possible for teacher to delete a registration.
It may be done easily, while adding an action in the "Registration status" view, as you have the "Grade" action, there could be a "Revoke registration" action, that triggers a confirmation box to confirm registration deletion.

With great thanks for this wonderful plugin.

**Comment by bluetom** [comment]
If an appointment is assigned to a student by a teacher a teacher is able to delete this appointment as well, otherwise not. A teacher is not allowed to delete a registration of a student.

**Comment by zabellemotte** [comment]
Why such a restriction ? Sometimes the students ask for a registration change and this does not impose the slot to be suppressed.

**Comment by zabellemotte** [comment]
If this is a critical point, you could add a new permission to enable this option or not :
mod/organizer:unregisterall

**Comment by zabellemotte** [comment]
As far as there is a relative deadline parameter, students are not more able to modify their slot once the deadline delay is reached. This makes the capability for teacher to modify slots necessary.

**Comment by zabellemotte** [comment]
I have been testing the latest version of organizer and I am very happy to note this issue is solved.
Great thanks @bluetom.

**Comment by zabellemotte** [comment]
I have been testing the latest version (4.3.1) of organizer and I am very happy to note this issue is solved. Great thanks @bluetom.
