### ISSUE TITLE
Organizer - PHP Warning:  Undefined property: stdClass::$digest

### ISSUE THREAD

**Issue by acquaalta** [academic-moodle-cooperation/moodle-mod_organizer#131]
Moodle version: 4.3
PHP version: 8.2
Organizer version: v4.3.1 or maybe 4.3.0 (For a technical reason, I can't verify it right now, but I know that I downloaded and installed the plugin a few days ago).

Hi,
The CRON of my Moodle test server sent me the following message:
PHP Warning:  Undefined property: stdClass::$digest in --PATH--/moodle/mod/organizer/lib.php on line 738
PHP Warning:  Undefined property: stdClass::$digest in --PATH--/moodle/mod/organizer/lib.php on line 741
PHP Warning:  Undefined property: stdClass::$digest in --PATH--/moodle/mod/organizer/lib.php on line 738
PHP Warning:  Undefined property: stdClass::$digest in --PATH--/moodle/mod/organizer/lib.php on line 741
PHP Warning:  Undefined property: stdClass::$digest in --PATH--/moodle/mod/organizer/lib.php on line 738
PHP Warning:  Undefined property: stdClass::$digest in --PATH--/moodle/mod/organizer/lib.php on line 741

I don't know what is the actual effect of it, if any, in the activity, but maybe it's something that should be fixed in the plugin code.

Thanks :-)

**Comment by bluetom** [comment]
Is fixed in the recently published organizer versions 4.3.2 and 4.4.1

**Comment by acquaalta** [comment]
@bluetom  Thank you ver much :-)
