### ISSUE TITLE
Organizer - When trying to see the registration status of a course with no students

### ISSUE THREAD

**Issue by acquaalta** [academic-moodle-cooperation/moodle-mod_organizer#132]
Moodle version: 4.3
PHP version: 8.2
Organizer version: v4.3.1 or maybe 4.3.0 (For a technical reason, I can't verify it right now, but I know that I downloaded and installed the plugin a few days ago).

Hi,
I discovered that when using the plugin in a course with no students, and then trying to access the "Registration status" tab , an exception is thrown. I assume that the plugin tries to display the students list, and faces an empty array/variable, and then the exception is thrown.
Is it possible to let the plugin handles that situation more softly, and display a message that the registration status can't be displayed since there are no students in the course?
And yes, I know that there is no sense in using the plugin in a course without students, but if this scenario could be covered, it would be nice :-)

Thanks :-)

**Comment by acquaalta** [comment]
Hi,
I'm adding a screenshot of the exception below:

![Oraganizer_NoParticipants_Exception](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/51836675/7500bd8c-c8b9-4e72-8d6c-69ca65c74086)

**Comment by acquaalta** [comment]
Hi,
I'm adding a screenshot of the exception:

![Oraganizer_NoParticipants_Exception](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/51836675/da623722-2f10-4a3a-9a9e-195a6e3492f2)

**Comment by bluetom** [comment]
Is fixed in the recently published organizer versions 4.3.2 and 4.4.1

**Comment by acquaalta** [comment]
@bluetom  Thank you ver much :-)
