### ISSUE TITLE
Features Request: Editing options for existing slots

### ISSUE THREAD

**Issue by Nukker1** [academic-moodle-cooperation/moodle-mod_organizer#133]
We have received feedback from several users that it would be helpful if it were easier to edit existing slots. It is currently not possible to change the time or day of an existing slot. Instead, the slot must be completely deleted and created again. Existing registrations are lost as a result. It would be much more useful if existing slots could be extended.

**Comment by bluetom** [comment]
This feature is part of the new organizer which will be published in summer 2024.
For the current (and last) version of the "old" organizer we called already a feature stop.
