### ISSUE TITLE
Feature Request: Managers can unregister students from slots

### ISSUE THREAD

**Issue by Nukker1** [academic-moodle-cooperation/moodle-mod_organizer#134]
It is possible for managers to assign students a time slot manually.  However, it is not possible for managers to manually unregister certain students from an slot without deleting the whole slot. It should therefore be possible for managers to unregister selected students from time slots.

**Comment by zabellemotte** [comment]
This issue is linked to
https://github.com/academic-moodle-cooperation/moodle-mod_organizer/issues/129

**Comment by zabellemotte** [comment]
I have been testing the latest version (4.3.1) of organizer and I am very happy to note this issue is solved. Great thanks @bluetom.
