### ISSUE TITLE
Organizer - When trying to see the registration status of a course with an empty grouping

### ISSUE THREAD

**Issue by acquaalta** [academic-moodle-cooperation/moodle-mod_organizer#136]
Hi,

Moodle version: 4.3.3
Plugin version: 4.3.1

**Repro Steps**
1. Enter a course with students.
2. Create a grouping in the course, but without assigning groups to it.
3. Create a new "Organizer" activity in the course.
4. Set the "Group appointments" setting to "Use existing course groups".
5. When asked to choose a grouping, choose the grouping that you created in item no. 2 above.
6. Create an appointment.
7. Go to the "Registration" tab.

**Actual Results**
An exception is thrown.

![Oraganizer_NoGroups_Exception](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/51836675/c3214913-49ee-4c1c-a64e-87323465deb4)

Could you please fix this?

Thanks :-)

**Comment by bluetom** [comment]
Is fixed in the recently published organizer versions 4.3.2 and 4.4.1

**Comment by acquaalta** [comment]
@bluetom  Thank you ver much :-)
