### ISSUE TITLE
Debug message when installing on Moodle 3.0

### ISSUE THREAD

**Issue by abias** [academic-moodle-cooperation/moodle-mod_organizer#14]
Hi,

as we are ahead of your release cycle, we will be using your plugin on Moodle 3.0 soon.

I am happy to inform you that mod_organizer (in its last version on https://moodle.org/plugins/pluginversions.php?plugin=mod_organizer) basically works on Moodle 3.0.

Just note that there is a debug message when adding an organizer activity to a course saying:

`Strict Standards: Declaration of mod_organizer_mod_form::standard_intro_elements() should be compatible with moodleform_mod::standard_intro_elements($customlabel = NULL) in /var/www/html/moodle_ng/mod/organizer/mod_form.php on line 34`

Thanks,
Alex

**Comment by mkemmerling** [comment]
Hi Alex,

good news, thanks for reporting! BTW: We plan to catch up with our release cycle to the most recent Moodle version until autumn this year.

**Comment by mkemmerling** [comment]
Fixed in the MOODLE_30_STABLE branch.
