### ISSUE TITLE
Re-register within relative deadline

### ISSUE THREAD

**Issue by hschnurbusch** [academic-moodle-cooperation/moodle-mod_organizer#142]
Hi, 

if I want to avoid that students can register or unregister from a slot at short notice I can set a relative deadline. The problem is that students can still re-register for another slot despite the relative deadline. 

This leads to problems for our tutors: They offer some slots very late in the day. Although there's a relative deadline of one day some students that had a late slot simply re-registered for another slot only one hour before. The tutors therefore have been waiting for nothing. 

Therefore it would be good to extend the setting also to re-registering. Technically spoken re-registering is also unregistering and registering for another slot in one action, i.e. it doesn't really make sense to allow this combination while not allowing single steps.

Best
Harald

**Comment by bluetom** [comment]
Hi Harald,
honestly spoken I would have expect it to work the way you propose... I add this request to our Version 4.5. backlog.
BR
Thomas

**Comment by bluetom** [comment]
After reproducing the case I can see clearer: 
The deadline is valid for each slot. You have registered for a slot where you can't unregister anymore because of the deadline. But as long as there are bookable slots far away in the future to avoid the deadline you can reregister for them!
...Well, I would say that is not a bug and I have to find a solution for that non-trivial problem...
BR,
Thomas

**Comment by hschnurbusch** [comment]
Hi Thomas, 

the problem I see is the following:

1. Create an organizer with a relative deadline of 5 minutes. 
2. Each student is allowed to register for one slot.
3. Create at least 2 slots of 5 minutes each.
4. The first slot is today from 3pm to 3.05pm. The second slot is from 3.05pm to 3.10pm.
5. Now register as a student for the first slot before the deadline.
6. You should see that you can unregister or re-register for a different slot until you reach the deadline.
7. A minute after the deadline has passed you cannot unregister from the first slot. But you can nevertheless re-register for the second slot, i.e. you are unregistered from the first slot and moved to the second. 

So you have basically canceled the appointment for the first slot without being allowed to do so. Now imagine the following situation: Students register for slots with their tutors in the late evening hours. The relative deadline is set to one day. So they should only cancel until one day in advance to avoid cancellations at short notice because the tutor is staying at university until 11pm just for this meeting. With the current behaviour a student can re-register for an appointment two days later (if there are slots left) just one hour before his original appointment. This is very frustrating.

Hope that helps to show the problem.

Best
Harald

The scheduler for example has a different interface that avoids this conflict. It forces you to cancel the appointment before you are allowed to book a different slot.

**Comment by bluetom** [comment]
I have already fixed it and I have a version for Moodle 4.3 ready. I don't know how long the publication takes, that is done by another member of the AMC. Do you want the fixed version from me...?

**Comment by hschnurbusch** [comment]
Hi, we can wait until mid-December. If it hasn't been published until then I'd be happy to accept your offer. But if it is easier for you to point me towards the fix now I'll take that, too. 

Thanks and have a nice evening
Harald

**Comment by bluetom** [comment]
Hi Harald,
the new organizer version 4.3.3 including this feature is online: https://moodle.org/plugins/mod_organizer/versions
lg,
Thomas
