### ISSUE TITLE
Students get notified constantly after the slot appointment is over

### ISSUE THREAD

**Issue by abias** [academic-moodle-cooperation/moodle-mod_organizer#15]
Hi,

we are running the latest version of this plugin from the Moodle plugins repo (https://moodle.org/plugins/pluginversions.php?plugin=mod_organizer) on Moodle 3.0, but this problem was already present when we ran the 2.8 version of the plugin on 2.9.

Several students are telling us that they are constantly notified about slot appointments which are definitely in the past. They are getting these notification mails multiple times per day, but as far as we see there is no "mail sending schedule scheme" like 1 notification mail every 2 hours.

Up to now, all of these student feedbacks can be traced back to one instance of mod_organizer in one course, but I am afraid that there might be a fundamental problem.

I had a look at the mdl_organizer_slot_appointments table (respectively mdl_organizer_appointments table on 2.9 if I remember correctly) and saw that _all_ of the entries there have a "0" value in the notified column. As soon as I change this value to 1 for a certain slot appointment, the student confirms that he does not receive any notifications anymore.

As a measure of precaution, I have now changed all values for "notification" to 1 in  mdl_organizer_slot_appointments for slot appointments which started in the past and hope that the problem is gone for these appointments.

Nevertheless, I would like to ask you to support us to check why the notified column is not set to 1 at all so that this problem does not arise again for new appointments.

Thanks,
Alex

**Comment by mkemmerling** [comment]
Hi Alex,

thanks for reporting. We, i.e. Thomas, will have a look at this issue. I hope we can provide a fix pretty soon.

Cheers,
Markus

**Comment by mkemmerling** [comment]
This is a database related bug. It happens with PostgreSQL, but not with MySQL. The bug has been fixed in the MOODLE_29_STABLE as well as in the new MOODLE_30_STABLE branches (including new features like a queuing list). Both versions have also been published on moodle.org.
