### ISSUE TITLE
Problem with the "Registration Status" view

### ISSUE THREAD

**Issue by benidroe** [academic-moodle-cooperation/moodle-mod_organizer#2]
When I click on the "Registration Status" view, I see only a debug-info:

Debug info: ERROR: column "a2.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 4: WHEN a2.id IS NOT NULL AND a2.attended = 1 AND a2.al...
^
SELECT DISTINCT
u.id, u.firstname, u.lastname, u.idnumber,
CASE
WHEN a2.id IS NOT NULL AND a2.attended = 1 AND a2.allownewappointments = 0 THEN 0
WHEN a2.id IS NOT NULL AND a2.attended = 1 AND a2.allownewappointments = 1 THEN 1
WHEN a2.id IS NOT NULL AND a2.attended IS NULL AND a2.starttime <= $1 THEN 2
WHEN a2.id IS NOT NULL AND a2.attended IS NULL AND a2.starttime > $2 THEN 3
WHEN a2.id IS NOT NULL AND a2.attended = 0 AND a2.allownewappointments = 0 THEN 4
WHEN a2.id IS NOT NULL AND a2.attended = 0 AND a2.allownewappointments = 1 THEN 5
WHEN a2.id IS NULL THEN 6
ELSE -1
END AS status,
a2.starttime, a2.duration, a2.attended, a2.location, a2.locationlink,
a2.grade, a2.comments, a2.teachercomments, a2.feedback, a2.teacherid,
a2.userid, a2.teachervisible, a2.slotid, a2.allownewappointments, a2.id AS appid
FROM mdl_user u
LEFT JOIN
(SELECT a.id, a.attended, a.grade, a.feedback, a.comments, a.userid,
a.allownewappointments, s.starttime, s.location, s.locationlink, s.teacherid,
s.comments AS teachercomments, s.duration, s.teachervisible, s.id AS slotid
FROM mdl_organizer_slot_appointments a INNER JOIN mdl_organizer_slots s ON a.slotid = s.id
WHERE s.organizerid = $3 ORDER BY a.id DESC) a2 ON u.id = a2.userid
WHERE u.id IN ($4,$5,$6)
GROUP BY u.id
ORDER BY status ASC, u.lastname ASC, u.firstname ASC, u.idnumber ASC
[array (
0 => 1394179455,
1 => 1394179455,
2 => '5',
3 => '458',
4 => '4527',
5 => '4380',
)]
Error code: dmlreadexception
Stack trace:
line 423 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 753 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 728 of /mod/organizer/view_lib.php: call to pgsql_native_moodle_database->get_records_sql()
line 739 of /mod/organizer/view_lib.php: call to organizer_organizer_get_status_table_entries()
line 156 of /mod/organizer/view_lib.php: call to organizer_organizer_generate_registration_table_content()
line 97 of /mod/organizer/view.php: call to organizer_generate_registration_status_view()

**Comment by Kathrin84** [comment]
Issue is fixed in within our Moodle -> can be closed.
Thanks.
