### ISSUE TITLE
Slots with duration > 36000 seconds (9h10m) are not possible

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#20]
Hi togheter,

it's me again. A teacher told us that it's impossible to create slots with a duration longer than 9 hours.

I tried it myself and came up with this debugging message:
![smallint](https://cloud.githubusercontent.com/assets/4711883/16143127/06fd2478-346b-11e6-89e7-321d8bfaaf95.png)

In the productive environment following message occurs and no slots are created:
![fehler_db](https://cloud.githubusercontent.com/assets/4711883/16143343/65ed8d00-346c-11e6-92e9-0c08df784cdd.png)

The cause is that the database field is defined as a smallint => so the max time of a slot is limited to 9 hours and round about 10 minutes.

I think this is a too strikt limitation.

How about setting the database field to int?

As a small feature request concerning this topic: How about adding a setting to easily allow whole day slots, analogous to usual calendary function?

Cheers,
Kathrin

**Comment by mkemmerling** [comment]
Thanks for reporting. The bug will hopefully soon be fixed.
I copied your feature request over to a separate issue #21.

**Comment by mkemmerling** [comment]
Hi Kathrin,

the smallint bug has been fixed in version 3.0.2 (2016050402). Please update.

Cheers,
Markus

**Comment by Kathrin84** [comment]
Thanks a lot for the quick fix. 👍
