### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by scouli** [academic-moodle-cooperation/moodle-mod_organizer#26]
i installed the moodle-mod_organizer plugin on our server with the moodle version 3.1. When i try to add a new slot, i always get a database writing error. We are using the postgresql 9.3.
The database logfile show this error (see screenshot).
![screenshot](https://cloud.githubusercontent.com/assets/21237316/17997830/4a830a86-6b71-11e6-8a02-52b0bd4af632.jpg)

**Comment by kaspot** [comment]
may I ask you which version of Organizer you are using? We have published the newest 3.1 version a couple of days ago. Maybe you could try with this version.

**Comment by kaspot** [comment]
Is this still an issue? If not I will close it.

**Comment by scouli** [comment]
You can close the issue, because  I think that the error come from our database.

Thanks.

Von: kaspot [mailto:notifications@github.com]
Gesendet: Dienstag, 20. September 2016 15:48
An: academic-moodle-cooperation/moodle-mod_organizer
Cc: Coulibaly, Souleymane; State change
Betreff: Re: [academic-moodle-cooperation/moodle-mod_organizer] database error (#26)


Is this still an issue? If not I will close it.

**Comment by kaspot** [comment]
ok thanks for the update.
