### ISSUE TITLE
Database Error on tab registration status with version 2016072102 on Moodle 3.1 and Postgres

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#27]
Hi there,

as in the title described we get the following database error message when clicking on the tab registration status:

`Debug info: ERROR: column "a2.teacherapplicantid" must appear in the GROUP BY clause or be used in an aggregate function
LINE 15: ....slotid, a2.allownewappointments, a2.id AS appid, a2.teacher...
^
SELECT DISTINCT
u.id, u.firstname, u.lastname, u.idnumber,
CASE
WHEN a2.id IS NOT NULL AND a2.attended = 1 AND a2.allownewappointments = 0 THEN 0
WHEN a2.id IS NOT NULL AND a2.attended = 1 AND a2.allownewappointments = 1 THEN 1
WHEN a2.id IS NOT NULL AND a2.attended IS NULL AND a2.starttime <= $1 THEN 2
WHEN a2.id IS NOT NULL AND a2.attended IS NULL AND a2.starttime > $2 THEN 3
WHEN a2.id IS NOT NULL AND a2.attended = 0 AND a2.allownewappointments = 0 THEN 4
WHEN a2.id IS NOT NULL AND a2.attended = 0 AND a2.allownewappointments = 1 THEN 5
WHEN a2.id IS NULL THEN 6
ELSE -1
END AS status,
a2.starttime, a2.duration, a2.attended, a2.location, a2.locationlink,
a2.grade, a2.comments, a2.teachercomments, a2.feedback, a2.teacherid,
a2.userid, a2.teachervisible, a2.slotid, a2.allownewappointments, a2.id AS appid, a2.teacherapplicantid, a2.teacherapplicanttimemodified
FROM mdl_user u
LEFT JOIN
(SELECT a.id, a.attended, a.grade, a.feedback, a.comments, a.userid,
a.allownewappointments, s.starttime, s.location, s.locationlink, s.teacherid,
s.comments AS teachercomments, s.duration, s.teachervisible, s.id AS slotid, a.teacherapplicantid, a.teacherapplicanttimemodified
FROM mdl_organizer_slot_appointments a INNER JOIN mdl_organizer_slots s ON a.slotid = s.id
WHERE s.organizerid = $3 ORDER BY a.id DESC) a2 ON u.id = a2.userid
WHERE u.id IN ($4,$5,$6,$7,$8)
GROUP BY u.id, a2.id, u.firstname, u.lastname, u.idnumber, status,
a2.starttime, a2.duration, a2.attended, a2.location, a2.locationlink,
a2.grade, a2.comments, a2.teachercomments, a2.feedback, a2.teacherid,
a2.userid, a2.teachervisible, a2.slotid, a2.allownewappointments
ORDER BY status ASC, u.lastname ASC, u.firstname ASC, u.idnumber ASC
[array (
0 => 1474461114,
1 => 1474461114,
2 => '52',
3 => '13112',
4 => '13113',
5 => '11964',
6 => '12089',
7 => '4526',
)]
Error code: dmlreadexception`

As already mentioned: We're operating on Moodle 3.1 with a Postgres DB.

Cheers, Kathrin

**Comment by kaspot** [comment]
thanks will forward this to our developer.

**Comment by mkemmerling** [comment]
Hi Kathrin,

thanks again for reporting. We just published a bug fix release 3.1.3 here and on moodle.org. With the error being fixed I close this issue.

**Comment by Kathrin84** [comment]
Thanks for the fix! Yes, now it's working as expected!
Cheers
