### ISSUE TITLE
Feature Request: Student ID Number should be invisible

### ISSUE THREAD

**Issue by gushagelberg2** [academic-moodle-cooperation/moodle-mod_organizer#28]
Presently a student's ID number (matriculation or registration number) is seen by all participants. It would be great if this was either removed or a setting created to make it invisible.
In Germany this is a privacy issue.
Thanks,
Gus

**Comment by kaspot** [comment]
Are you referring to seeing each others matriculation number as a student? So you would like them to see each others name but not matriculation number, right? If yes, then maybe an option would be to use the setting "Anonymous: The members of this slot are always invisible to all." That's a setting that should keep it anonymous. I know that it's not exactly what you asked for, but maybe a workaround for now. 
So can you describe a little bit more in detail what your proposed solution would be, then I could add it as a feature request for a future planning meeting.

**Comment by kaspot** [comment]
May I ask you to give us more details as mentioned in the previous comment, that would be really helpful.

**Comment by kaspot** [comment]
Closing because no further details.
