### ISSUE TITLE
Limit upcoming event

### ISSUE THREAD

**Issue by yvanleduc** [academic-moodle-cooperation/moodle-mod_organizer#29]
Bonjour,
Thanks for this plugin ... it meets our needs. Teachers write their availability and students reserve certain time slots. The student sees in his list of upcoming events the appointments he has made. On the other hand the teacher sees in his list of events to come all the time slots where he is available. Since there is a lot of availability and relatively few appointments the list of upcoming events is filled with empty time slot (without an appointment). My question is: Is it possible for the teacher to limit his list of upcoming events to see only the time slots for which there are appointments. We use Moodle 3.2 and version 3.1 (2016071100) of the Organizer plugin.
Thank you
Yvan Leduc

**Comment by bluetom** [comment]
Bonsoir,
up till now (organizer version 3.2) there is only the opposite filter option "free slots".
With the upcoming organizer version 3.3 some new filter options will be introduced: 

- free/taken
- available/not available

Best regards,
Thomas

**Comment by bluetom** [comment]
Sorry, I closed this issue by mistake...!

**Comment by yvanleduc** [comment]
Thanks for your answer...when can we expect the 3.3 version?

2017-04-05 18:28 GMT-04:00 bluetom <notifications@github.com>:

**Comment by bluetom** [comment]
The publication of organizer version 3.3 is planned for August/September 2017.

**Comment by bluetom** [comment]
Hi Yvan,
I wonder if I've got you right. 
Do you mean by "list of events to come"
- the events in the moodle calendar
- the organizer's "slot overview" view or
- the list of upcoming tasks in the "course overview" "timeline" list of the dashboard?
Best Regards,
Thomas

**Comment by yvanleduc** [comment]
Évents in thé Moodle calender

Thanks

**Comment by goggo24** [comment]
@yvanleduc with organizer 3.5.+ as a teacher you have a setting **"No calendar events for empty slots"** to prevent creating empty slot calendar events. Therefore i close this issue. Eva
