### ISSUE TITLE
Trying to install gives "Invalid Plugin Name Error"

### ISSUE THREAD

**Issue by derekc** [academic-moodle-cooperation/moodle-mod_organizer#3]
Using the 2.7 version.

-Derekj

**Comment by derekc** [comment]
![image](https://cloud.githubusercontent.com/assets/687780/6792931/c0e32da8-d222-11e4-9f3f-316b5321b809.png)

**Comment by kaspot** [comment]
Have you tried the newest version?

**Comment by kaspot** [comment]
Please try the newest version - we are closing this issue. If the problem remains, please create a new issue with the newest version.
