### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by yvanleduc** [academic-moodle-cooperation/moodle-mod_organizer#31]
Hi,

We use the version v3.2.2 of organizer in Montreal (Canada). Our version of Moodle is 3.2

There is a problem with the display of the date the when Moodle send email about appointements.

Actually our message is shown like this:

_Bonjour Amadeus Mozart, Vous avez un rendez-vous avec Éric Savoie le **306.11.jeudi** à 10:00 au Local 302. Système de messagerie Moodle_

But it should be like this:

_Bonjour Amadeus Mozart, Vous avez un rendez-vous avec Éric Savoie le **jeudi 2.11.2107** à 10:00 au Local 302. Système de messagerie Moodle_

Is it possible to put the date in the format: Friday 25.12.2017...i cannot understand what is the number 306 .11.  

Thanks for your help

**Comment by kaspot** [comment]
Hi there, 
thanks for reporting this issue. Can you give us more detailed information on your system details, DB, PHP version etc. so that we can figure out what the problem is. 
I will then add this issue to our ticketing system. 
Thanks again.

**Comment by yvanleduc** [comment]
Hi, I have fixed the problem..there was a error in the french language package when writing the format of the date for the chain **appointment_reminder:student:fullmessage**

Thank you

**Comment by kaspot** [comment]
Thanks for letting us know what the problem was and happy for you that it is working now.
