### ISSUE TITLE
Error message when trying to activate notifications preferences

### ISSUE THREAD

**Issue by yvanleduc** [academic-moodle-cooperation/moodle-mod_organizer#33]
Hi,
 We use Moodle 3.2 and version 3.2.2 (2017013102) of the Organizer plugin.  When i try to change my preference setting to be able to be notified when a student book an appointment i get an error message (invalid parameter).

![image](https://user-images.githubusercontent.com/26931536/33563816-e7ce2846-d8e6-11e7-9411-27a0f717785b.png)

![image](https://user-images.githubusercontent.com/26931536/33563894-1e20b710-d8e7-11e7-969e-e412dbf8b1c2.png)

Any idea?

Thank you

**Comment by bluetom** [comment]
Hi,
this bug is fixed with this commit: https://github.com/academic-moodle-cooperation/moodle-mod_organizer/commits/MOODLE_33_STABLE?after=5ab1acd8529d070f29946e782be89874d518cfbc+34. 
Unfortunately it's part of the organizer stable version 3.3...
Regards,
Thomas

**Comment by yvanleduc** [comment]
Thank you

2017-12-05 10:56 GMT-05:00 bluetom <notifications@github.com>:
