### ISSUE TITLE
Decription text not processed by filters

### ISSUE THREAD

**Issue by ahruska** [academic-moodle-cooperation/moodle-mod_organizer#34]
Description text in organizer ist NOT processed by moodle filters.
This was discoverd using the Multilang2 Filter Plugin ... {mlang XX} remain unprocessed.
Plz apply moodle filters to description as well.

Best regards
Andreas

**Comment by kaspot** [comment]
We added this issue to our backlog. Thanks for reporting it.

**Comment by mkemmerling** [comment]
Fixed with releases 3.3.5 and 3.4.2.
