### ISSUE TITLE
Bug in messaging with group mode

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#35]
Hi at all,
we encountered a bug with the outgoing email message in combination with groups enabled in the organizer.

This is our scenario:
There are several groups and groupings within the course. A user is member of two groups of two different groupings. The organizer is set to group mode with one of those groupings.

The student registers his group for a time slot. Within the organizer, the correct group is shown:
![selected_slot](https://user-images.githubusercontent.com/4711883/34989539-3286abb2-fac3-11e7-837c-8748e2127284.png)

Unfortunately, the message the teacher received was for the other user's group membership (and which is not used in the organizer):
![received_message](https://user-images.githubusercontent.com/4711883/34989580-65ae810e-fac3-11e7-82a5-745e9af89319.png)

The cause is probably that you call the groups within the messaging.php and then reset it to the first group: https://github.com/academic-moodle-cooperation/moodle-mod_organizer/blob/master/messaging.php#L107

Because the database query of the called function does not sort the result (https://github.com/moodle/moodle/blob/5f54a8760f2821c12bd90beaa37b9fa937f101e6/lib/grouplib.php#L481) any group the user is a member in could be listed as the first item and is then used for the message.

A better way would be to pass the organizer related group to the organizer_send_message function.

I hope this was understandable. 

Best, Kathrin

**Comment by kaspot** [comment]
Dear Kathrin, 
thank you so much for this very detailed bug report - that's how we like to get those ;-)
I will immediately create a new issue in our Bug Tracking system, may I just ask you to give me more infos on which version of the Organizer & Moodle this is happening. Thanks.

**Comment by Kathrin84** [comment]
Hi Kasia,
I've tested it with those versions:
* Organizer: 2017120500
* Moodle: 2017111300.1 (Moodle 3.4+ Build: 20180104)

**Comment by Kathrin84** [comment]
Hi Kasia,

I'm not quite sure right now - is this bug fixed with this commit: https://github.com/academic-moodle-cooperation/moodle-mod_organizer/commit/3f4a6f060f8af936313fbbf8bad4e02ab0939a5c?
This change log entry seems to address this issue:
[FIXED] #5231: Getting wrong user group when messaging in group mode

Is this correct? If this bug is fixed the issue can be closed, of course.

Best, Kathrin

**Comment by abias** [comment]
Hi @kaspot ,

I would like to second Kathrin's question if this bug was already fixed with the referenced commit or not. Do you have any news for us?

Thanks,
Alex

**Comment by goggo24** [comment]
fixed since v.3.3.4+
