### ISSUE TITLE
Take a look at images

### ISSUE THREAD

**Issue by dinism** [academic-moodle-cooperation/moodle-mod_organizer#36]
# FIRST
In string "eventtemplatewithoutlinks" you have Ort:
Not english but deutch
"Dieser Ort kommt mir bekannt vor, ich muss hier schon einmal gewesen sein."
I think you mean "Location:"
I'm Portuguese (PT) translator. No problem.
THANKS

# SECOND
Please, take a look here:
https://imgur.com/a/PhLOz

**Comment by kaspot** [comment]
Thanks for reporting those issues. I forwarded those to our developer.

**Comment by dinism** [comment]
# One suggestion: 
Disable evaluate when "This slot has not occurred yet"

**Comment by goggo24** [comment]
fixed in v.3.4.1. => $string['eventtemplatewithoutlinks'] = '{$a->coursename} / {$a->organizername}: {$a->appwith} {$a->with} {$a->participants}<br />Location: {$a->location}<br />';

**Comment by dinism** [comment]
This only happens with **https**. With **http** is OK

**Comment by goggo24** [comment]
- eventtemplatewithoutlinks  => fixed in 3.4.+
- Strings min/mins  => are now used correctly - 1 min / 15 mins
- time left hide 0 days => not implemented yet, no functional impairment - added to our backlog with low priority

Thanks for reporting!
