### ISSUE TITLE
Organizer stays on Dashboard even after the deadline

### ISSUE THREAD

**Issue by roessling** [academic-moodle-cooperation/moodle-mod_organizer#39]
Hi,
the Organizer seems to stay on the Dashboard even after the active "due date" has passed, and if the option "Always show description" is set to "off". I think that in these cases, it should be possible - either by using the "always show description" option or in some other ways - to remove the activity from the Dashboard once it has expired. (It is still shown on the Dashboard using block_course_overview_campus although it expired more than 6 months ago...)
Thanks!

**Comment by goggo24** [comment]
@roessling Does this behavior still occur? 
I just tried it with an old organizer instances (passed due date 3 months ago) in moodle core 3.5.x. The "passed" organizer doesn't appear on the dashboard - i tried it with course overview block and our own block_semester_sortierung.

**Comment by roessling** [comment]
I think it's gone - thanks!
