### ISSUE TITLE
Problem with time on creating slots

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#4]
Hi,

I'm trying out your plugin. Installation and creating a new organizer works well. I have problems with the time slots. 
When I want to have timeslots for 12:00 - 14:00 p.m. the system creates slots 2 hours in the future from 14:00 - 16:00 p.m.

![organizer_slot_settings](https://cloud.githubusercontent.com/assets/4711883/8159127/1b3aa8e4-1364-11e5-8600-b14ad33712f6.png)
![organizer_slot_results](https://cloud.githubusercontent.com/assets/4711883/8159130/1e2bfe86-1364-11e5-8e72-c17409b4df59.png)

The same with other times...

Best regards

**Comment by kaspot** [comment]
I think in our newest version this bug is already fixed. Have you tried our newest version? At least in the newest 28 version, which will come end of August it should definitely be fixed.

**Comment by Kathrin84** [comment]
I'm using this Version:
2014-01-21 (2015012100)Moodle 2.7
Release date: Wednesday, 18 March 2015, 9:52 PM

We're running Moodle 2.8, so we'll then try the lastest version when it will be released at end of August.

**Comment by kaspot** [comment]
Dear Kathrin, the newest version of the Organizer is now available on github. Please share your insights with us.

**Comment by Kathrin84** [comment]
Hi Katarzyna,

I've installed your latest version of the plugin and tested it with Moodle 2.9.
There everything works fine concerning this time issue.

The admin has also to remember to set the time zone in Moodle correctly so that the displaying is correct in countries with different times for summer and winter.
If this is set correctly, the time show the correct time. :)

This ticket then can be closed. 

Kind regards,
Kathrin

**Comment by kaspot** [comment]
Thanks Kathrin for testing it - and I'm really happy that it works fine for you.
Closing.
