### ISSUE TITLE
Bug: Change in availability timespan not updated in calendar

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_organizer#42]
Create an Organizer activity with a set registration start and end time. This creates an appropriate amount of course events in the calendar. If you then edit the activity and change the day of the registration end, the events in the calendar are not updated, i.e. events are neither deleted nor are any new ones created.

**Comment by do-you-even-curl** [comment]
I just noticed that the same applies to the activity name. The names of the calendar events don't get updated when you change the name of the activity.

**Comment by goggo24** [comment]
The change in the name of an organizer or to a registration date are properly updated in the calendar events now (v.3.5.0+). Thanks for reporting!
