### ISSUE TITLE
Feature "Print slot user fields": Multi language processing of custom user profile fields is missing

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#44]
Hi,

when trying out your new feature "Print slot user fields", we've encountered that custom user profile fields do not process multilang strings:
![multilang](https://user-images.githubusercontent.com/4711883/45080949-5936b100-b0f6-11e8-94d9-5b5ad1d19785.png)

It should easily be fixed by using the function format_string() on the table headings.

Best, Kathrin

**Comment by goggo24** [comment]
Same as #43. We won't fix it at the moment. If you provide a pull request, we are happy to pull it.

**Comment by abias** [comment]
Hi Eva,

thank you for your feedback.

I am happy to announce that Ulm University will contract a Moodle partner to have this issue solved and submitted to you as Github pull request.

Cheers,
Alex

**Comment by goggo24** [comment]
included in v.3.8.2 - have fun
