### ISSUE TITLE
Missing strings in AMOS

### ISSUE THREAD

**Issue by abias** [academic-moodle-cooperation/moodle-mod_organizer#45]
Hi there,

with the latest 3.5 release of mod_organizer, you have removed the german language pack from the plugin codebase to have the plugin fully translated in AMOS which is really appreciated.

However, I have seen that over 1 month after the release of this version, there are still 27 german strings untranslated in AMOS for this plugin. As these strings are mostly targeted at special areas and the privacy API, I hesitate to translate them myself.

Would you be so kind to complete the german language pack in AMOS?

Thanks,
Alex

**Comment by goggo24** [comment]
Hey Alex, yes, we changed our [de] langstring workflow of all our plugins ;) Because of time constraints we had in 3.5. the privacy langstrings only in english. We will rework the german ones in amos, so the german langstrings should follow soon. Liebe Grüße aus Wien, Eva

**Comment by abias** [comment]
Thanks, Eva, for your feedback and the hard work :)

**Comment by abias** [comment]
Hi Eva,

may I ask about the status of the translations in AMOS? As far as I see, there are still several strings untranslated in 3.5 and 3.6 - not only for the privacy API.

Cheers,
Alex

**Comment by goggo24** [comment]
Amos Contribution have been accepted - no missing german langstrings anymore (v.3.5.+).

**Comment by abias** [comment]
Great to hear that. Thanks, Eva!
