### ISSUE TITLE
Deprecated class 'core_search\area\base_activity' detected in search/activity.php

### ISSUE THREAD

**Issue by top-ender** [academic-moodle-cooperation/moodle-mod_organizer#46]
The class '`core_search\area\base_activity`' is deprecated. The usage of Organizer module in Moodle 3.6 produces a PHP fatal error due to this class.

The class is renamed to '`core_search\base_activity`'. With this minor change in `classes/search/activity.php` everything works fine.

(see also: https://tracker.moodle.org/browse/CONTRIB-6933)

**Comment by goggo24** [comment]
Organizer v3.6.0 has been released 4 weeks ago , the error shouldn't appear any more. Thanks for reporting!
