### ISSUE TITLE
Issues with cron in Version 3.5 and current master

### ISSUE THREAD

**Issue by phager-at** [academic-moodle-cooperation/moodle-mod_organizer#50]
In organizer_send_message_from_trainer() the DB table is mistakenly called organizer_slot_teacher instead of organizer_slot_trainer, preventing e-mails from being sent via cron job!

This affects version for 3.5 as well as current master/3.6!
See pull requests #48 & #49

**Comment by goggo24** [comment]
Thanks for reporting, we will include it in our next minor releases.

**Comment by goggo24** [comment]
Fix will be included in v.3.5.5+ and v.3.6.1+ - coming soon!
