### ISSUE TITLE
Re-assign student to other slot not possible

### ISSUE THREAD

**Issue by mariofroeschl** [academic-moodle-cooperation/moodle-mod_organizer#53]
The following process worked in Moodle+Organizer v3.5.2, but does not work anymore in v3.5.5:

1. Teacher T assigns slot A to student S.
2. S is notified about appointment A.
3. S does not take part in A.
4. T evaluates A and allows new appointment for S.
5. T assigns slot B to S.
6. S is notified about appointment B.

In v3.5.5 step 1 to 4 is OK, but 5 and 6 does not work (even though it says 5 worked). See error message attached.

![reassign_student](https://user-images.githubusercontent.com/49024713/57132375-a95a3600-6d9f-11e9-9f8a-c4eb4edf5e11.png)

**Comment by goggo24** [comment]
Thanks for reporting! This error occurred due to another fix - organizer versions 3.5.5. and 3.6.1. are affected :(  We are already working on this issue and will publish the fix asap it in our next minor releases for v.3.5.x. and v.3.6.x.

**Comment by goggo24** [comment]
Fix included in v.3.5.6 and v.3.6.2 - coming soon!
