### ISSUE TITLE
PHP warning when running cronjob

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_organizer#55]
> PHP Warning:  A non-numeric value encountered in /var/www/html/moodle/mod/organizer/lib.php on line 998

Stems from https://github.com/academic-moodle-cooperation/moodle-mod_organizer/blob/ba84dc2d51338dc76fa70f76b8973e28afbc3a81/lib.php#L998 when digest is set to 'never' (default).

This doesn't break anything, just creates a warning.

**Comment by goggo24** [comment]
Thanks for reporting and providing a pull request. We will have a look!

**Comment by abias** [comment]
I would like to second this report, we are seeing this problem as well.

**Comment by goggo24** [comment]
We scheduled it for v.3.7.0.
