### ISSUE TITLE
Reminder Message for Students is gramatically wrong

### ISSUE THREAD

**Issue by 12345-alt** [academic-moodle-cooperation/moodle-mod_organizer#58]
Moodle Messaging System: Automatic generated reminder email (send from trainer to student) is grammatically wrong: The name of the trainer is missing even though it's indicated in Moodle. Also, the punctuation don't seem correct **[proposed amendments in brackets and in bold]**

Example (german):

Hallo xx! **[,]**

Im Rahmen des Kurses **"**Testkurs**"** haben Sie einen Termin mit **[trainer]** am 20.06.2019 um 09:15 im/in e1.

Moodle Messaging System

Der Terminplaner ist unter diesem Link verfügbar.

**Comment by goggo24** [comment]
Thanks for reporting. We will have a look and insert the name of the trainer.

**Comment by goggo24** [comment]
Hey, we just tested this issue - with v.3.6.x it works fine. Which version do you use?

**Comment by 12345-alt** [comment]
Hello, 
Thank you for treating the issue. We currently use 3.6, but we will have an update to 3.7 soon. You will find a screenshot of the mail attached. 

![Screenshot_](https://user-images.githubusercontent.com/51990889/61770013-79de2700-adec-11e9-95dd-d2699b862aa0.PNG)

**Comment by goggo24** [comment]
Strange. Hopefully the update will solve the problem. Please, let us know after your update, if the bug still occurs or not. If yes, we will have a look - maybe it's a combination of different settings.

**Comment by 12345-alt** [comment]
Hello,
we just updated to 3.7 in our demo version (moodle-dev) and to bug is still occuring. Can you have a look?
Thank you!

**Comment by goggo24** [comment]
Which organizer version do you use?

**Comment by 12345-alt** [comment]
v3.6.2 (2019020802), Release date: Saturday, 18. May 2019, 21:14

**Comment by goggo24** [comment]
v.3.7.0 from organizer will be published soon - can you try it then with this version? In our tests  with this version everything looks fine. Thanks.

**Comment by goggo24** [comment]
I close this issue, becaue no new feedback appeared and in our instance it works fine.
