### ISSUE TITLE
Participation when unenrolled from course

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_organizer#59]
You can sign up as a participant for a future appointment, then get unenrolled from the course and still be listed as a participant for this future appointment.

This is confusing for the teacher because the participants list no longer reflects who's actually planning to show up at the appointments. I'd say either there should be some indicator showing when participants are no longer in the course or they should be automatically removed as participants. The latter could probably be done asynchronously with https://docs.moodle.org/dev/Event_2#Event_observers.

**Comment by goggo24** [comment]
Thanks for reporting. I just tried it and you are right, the user is still listed in the appointment. We will add it to our backlog.

**Comment by goggo24** [comment]
Thanks for reporting. I just tried it and you are right, the user is still listed in the appointment. We will add it to our backlog.

**Comment by goggo24** [comment]
fix included in v.3.11.2 - thanks for reporting.
