### ISSUE TITLE
Upgrading from 3.0.3 Fails because of missing column

### ISSUE THREAD

**Issue by davidpesce** [academic-moodle-cooperation/moodle-mod_organizer#62]
When upgrading from v3.0.3 to v3.5.6 (2018081006), I get the following error:
```
Debug info: Unknown column 'hidecalendar' in 'mdl_organizer'
ALTER TABLE mdl_organizer ADD nocalendareventslotcreation SMALLINT(4) DEFAULT 0 AFTER hidecalendar
Error code: ddlexecuteerror
```
I manually added the hidecalendar column with the values in install.xml and the upgrade process worked.

**Comment by goggo24** [comment]
closed -  Bug fixes for security issues in Moodle Core 3.5.x ended 10 May 2021, we use the same rhythm for our AMC plugins.
