### ISSUE TITLE
Fatal error when creating an organizer instance with separate/visible groups and a student in multiple groups

### ISSUE THREAD

**Issue by abias** [academic-moodle-cooperation/moodle-mod_organizer#66]
Steps to reproduce:
* Login as admin
* Create a course C
* Create users S1 and S2 and T
* Enrol user S1 and S2 into the course C with the student role
* Enrol user T into the course C with the teacher role
* Login as user T
* Go to course C
* Create one course grouping G
* Create two course groups G1 and G2
* Add the two course groups G1 and G2 to the course grouping G
* Add user S1 to the course group G1 
* Add user S2 to the course group G1 _and_ G2
* Create a new organizer instance with the following settings:
** Group appointments: Use existing course groups
** Group mode: Visible groups OR separate groups
** Grouping: Course grouping G
** Save and display

Expected result:
There is a clean error message telling the teacher that users cannot belong to multiple groups within the same grouping.

Actual result:
There is an error page saying `Fehler: Call to undefined function organizer_get_user_email().`

Reason:
You forgot to include `view_lib.php` in `mod_form.php`

Hotfix:
See https://github.com/moodleuulm/moodle-mod_organizer/commit/b42078c3ff473d39e3d98413b88f5ceae63a4193

**Comment by goggo24** [comment]
Thanks Alex, for letting us know. We will have a look at your solution and integrate it as soon as possible!

**Comment by goggo24** [comment]
Alex solution is included in v.3.7.1, v.3.6.3 and 3.5.8 - have fun!

**Comment by goggo24** [comment]
3.7.1 is now published
