### ISSUE TITLE
Feature Request: make connection to gradebook optional

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#7]
Hi,

it would be great if the trainer could decide if he wants the appointments to be connected to the gradebook or not.
If a trainer wants to use your plugin for scheduling, but has no intention to grade the appointments, the entry of the instance blows the gradebook unnecessarily up.

So it would be great if the connection would be an additional option to set or not to set.

Kind regards,
Kathrin

**Comment by Kathrin84** [comment]
Sorry, just this moment I saw, that the option is already there, so I'll immediately close this issue.

**Comment by kaspot** [comment]
Thanks for bringing this up and yes, there is already a setting in our module, where you can connect it to the gradebook as for other moodle modules.
