### ISSUE TITLE
Calendar Event Creation - Slot vs Appointment

### ISSUE THREAD

**Issue by dharmsworth** [academic-moodle-cooperation/moodle-mod_organizer#77]
[Possible enhancement] When creating a new organiser slot for >1 student (we tend to have 6-12 max participants per slot) we get a calendar full of appointments. Is it possible to disable 'appointment' events and just have one course-wide 'slot' event for each one, not sure if this is in fact the intended behaviour but students will get the full set of appointments in their calendar feed as well (if 8 students are registered they'll get 9 events [includes the teacher appointment] ).

Moodle 3.8.1+ (Build: 20200214)
Organizer 3.8.0 (Latest on MOODLE_38_STABLE branch)

**Comment by bluetom** [comment]
In a later organizer version the option "don't create calendar events for empty slots" was introduced. I hope this helps.
