### ISSUE TITLE
Request: Organizer on the front page

### ISSUE THREAD

**Issue by yvanleduc** [academic-moodle-cooperation/moodle-mod_organizer#78]
Thank you very much for this plugin, it is very useful to us. We are using version v3.5.8 with Moodle 3.5. I put an activity organizer on the front page. Everything works fine except that students do not receive notifications. This is because the roles on this front page do not appear in the role_assignments table. I read this the code (lib.php) :

 // FIXME replace this one with an alternative over capabilities.
function organizer_is_student_in_course($courseid, $userid) {
    global $DB;

    $stud = $DB->get_records_sql(
        'SELECT * FROM {role_assignments}
            INNER JOIN {context} ON {role_assignments}.contextid = {context}.id
            WHERE {role_assignments}.roleid = 5
                AND {context}.instanceid = :courseid
                AND {role_assignments}.userid = :userid', array('courseid' => $courseid,
        'userid'   => $userid)
    );
    return count($stud) > 0;_

Is there a way to modify that function so that students will be notify. Any fix avalaible ?

Thank you

**Comment by bluetom** [comment]
Can't find this function in the current organizer code anymore. This issue should be fixed.
