### ISSUE TITLE
Appointments are booked as course events

### ISSUE THREAD

**Issue by roessling** [academic-moodle-cooperation/moodle-mod_organizer#79]
I have used this plugin for a long time without issues. However, since the last update of Moodle (weekly build, 20200605) today or yesterday, bookings are marked as "course events" (type "Appointment", but visibility on the course level). This is especially annoying because I use this as a student advisor for (often very sensitive) topics, and many students do not want to let others see that/if they have an appointment.
I assume that this comes from the nightly update to Moodle, but is still probably something you need to look into.

**Comment by goggo24** [comment]
Thanks for reporting. I could reproduce the bug, we will have a look!

**Comment by goggo24** [comment]
fix included in v.3.11.2 - thanks for reporting.
