### ISSUE TITLE
Feature Request: add possibility to offer alternative slots to students whose slots have been deleted

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#8]
Hi,

in your plugin, it's possible to delete a slot even if a student is already registered to it. If deleted, a message is sent to this student registered on the slot.

It would be great, if the trainer who cancels the slot, could propose one or more alternative slots to those students who have been cancelled. If those alternative slots could be exclusively reserved to those students, it would help them to get a new slot - especially if all  other students are already registered to a slot and there aren't many free slots left.

Kind regards
Kathrin

**Comment by mkemmerling** [comment]
Hi Kathrin,

thank you for bringing this up. I forwarded your feature request to our developers to see if it can be implemented in the 29 version of the plugin.

**Comment by Kathrin84** [comment]
Hi,

I've tested your latest release and this feature is not yet implemted. So I keep my request open.

Kind regards
Kathrin

**Comment by kaspot** [comment]
Hi Kathrin, we do not have these use cases at our universities, so unfortunately the AMC decided to not implement this feature for now. If the student opens the organizer he/she can filter and display all free slots which should be a good compromise to have a nice overview of all available slots. Sorry.

**Comment by Kathrin84** [comment]
Hi, 
thanks for your response. I don't know if you would like to close this issue or keep it open for eventual later development?

**Comment by kaspot** [comment]
Hi Kathrin, I would prefer to close it, so that we have a clean board :-) if that's ok for you.

**Comment by Kathrin84** [comment]
I'll close.
