### ISSUE TITLE
Undefined function: organizer_get_eventaction_student

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_organizer#81]
When a student, i.e. a user without the capability "mod/organizer:viewregistrations" goes to the index.php of this plugin he gets this error:

```
Exception - Call to undefined function organizer_get_eventaction_student()
```

**Comment by goggo24** [comment]
Thanks for reporting. We will have a look!

**Comment by goggo24** [comment]
already fixed - v.3.9.+
