### ISSUE TITLE
Course name instead of shortname

### ISSUE THREAD

**Issue by rschrenk** [academic-moodle-cooperation/moodle-mod_organizer#82]
Hello,

in line https://github.com/academic-moodle-cooperation/moodle-mod_organizer/blob/master/view.php#L60 you implement the output of course shortname as page heading. Is there a specific reason for that? I was asked by users of our Moodle site if it would be possible to use the course name instead, wouldn't that be more user friendly?

Kind regards
Robert

**Comment by rschrenk** [comment]
Hello,

it is the view.php of your plugin, as I referenced in my first issue. In our case the shortnames of the courses are chosen automatically and contain a hashcode to ensure uniqueness. Therefore mod_organizer does not look very user friendly. 

Here are two screenshots, one showing the course page, one showing an organizer.
![course-page](https://user-images.githubusercontent.com/8080807/140068177-9f8f5ed4-ba39-4be4-9c52-afaf37dc4c10.png)
![mod-organizer](https://user-images.githubusercontent.com/8080807/140068184-7194073d-4617-4be8-ac26-0da56f33a72b.png)

It would look nicer, if mod_organizer would also use the courses fullname. It is a small modification in line 60 of view.php.

Kind regards

Robert

**Comment by rschrenk** [comment]
This is how users would expect it to be..
![mod-organizer-2](https://user-images.githubusercontent.com/8080807/140068536-438548ce-deb9-43a4-bc33-9ba508b776ad.png)
.

**Comment by bluetom** [comment]
Sorry, I missed this issue. If it comes to a new (last) patch version of this "old" organizer (which is build completely new at the moment) I will fix this.

**Comment by bluetom** [comment]
This is fixed in the new version 4.2.2, which has been published today: https://moodle.org/plugins/mod_organizer/versions
