### ISSUE TITLE
Add slot: Selecting trainer is not enforced

### ISSUE THREAD

**Issue by mariofroeschl** [academic-moodle-cooperation/moodle-mod_organizer#83]
On Moodle 3.5.12/ Organizer 3.5.8:

When adding a new slot, it can be saved without selecting a trainer (although a red icon next to it says "Required"). In this case it leads to an issue, that some mails are not sent to participants, where usually the trainer is used as sender (e.g. promoted from queue).

**Comment by goggo24** [comment]
Thanks for reporting. The trainer field is not required anymore and since v.3.7.x  the icon is removed. We won't fix it for 3.5.x - because it's not a supported moodle core version anymore.

**Comment by mariofroeschl** [comment]
@goggo24 
If no trainer is selected, it will cause another issue:
https://github.com/academic-moodle-cooperation/moodle-mod_organizer/issues/94

**Comment by bluetom** [comment]
Both issues have been fixed some versions ago.
