### ISSUE TITLE
Undefined function "fullusername"

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_organizer#84]
When you try to print a slot with the the user field "User full name" you get this:

> Exception - Call to undefined function fullusername()

**Comment by goggo24** [comment]
Thanks for reporting. We haven't selected user fullname in our printsetting, so the error didn't appear in our instance. I could reproduce the bug - we will have a look. Cheers, Eva

**Comment by goggo24** [comment]
Fixed in v.3.10.1 - have fun.
