### ISSUE TITLE
re register in a slot

### ISSUE THREAD

**Issue by aegea1500** [academic-moodle-cooperation/moodle-mod_organizer#88]
I'm using moodle version 3.4 and i installed organizer v3.4.3 and the students can't re register in a slot. when a student is registered in a slot they can't re register in other day slot. I see that bug fix is resolved in other versions. It's posible resolved this in my version ? thanks a lot

**Comment by goggo24** [comment]
Sorry, we are supporting as Moodle only versions 3.9 and 3.10 - for security issues 3.5 and 3.8. We won't fix this in v.3.4.3.
Therefore i will close this issue, because it's already fixed in newer versions.
