### ISSUE TITLE
Deprecation Warning in Moodle 2.9 when adding an instance to Moodle 2.9

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#9]
Hi there,

here's the following message:

Function moodleform_mod::add_intro_editor() is deprecated, use moodleform_mod::standard_intro_elements() instead.
•	line 710 of /course/moodleform_mod.php: call to debugging()
•	line 76 of /mod/organizer/mod_form.php: call to moodleform_mod->add_intro_editor()
•	line 195 of /lib/formslib.php: call to mod_organizer_mod_form->definition()
•	line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
•	line 255 of /course/modedit.php: call to moodleform_mod->moodleform_mod()

**Comment by kaspot** [comment]
Thanks for the feedback - we will forward this issue to our developer.

**Comment by kaspot** [comment]
Hi Kathrin, this issue should be fixed in the newest MOODLE_29_STABLE.
