### ISSUE TITLE
Request URI too long

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_organizer#90]
When I create 624 slots at once (in Chrome) I get an error stating the Request URI is too long. It's over 10000 characters long. However, the slots are still created. The organizer should probably transmit this data through POST parameters.

**Comment by goggo24** [comment]
Thanks for reporting. I could reproduce the bug - we will have a look! Eva

**Comment by goggo24** [comment]
Fixed in v.3.10.1 - have fun.
