### ISSUE TITLE
Slot overview filters not intuitive

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_organizer#91]
It is not obvious that the filter checkboxes are ANDed together rather than ORed. Many users select all checkboxes and wonder why they can't see any slots. Plus the message displayed is not so good either. It says there are no timeslots. It should say no timeslots match the filter criteria.

![image](https://user-images.githubusercontent.com/24255259/106183269-4e39bb00-61a0-11eb-98ef-6a48b7978af9.png)

**Comment by goggo24** [comment]
I agree totaly - thanks for reporting. A filter improvement issue was already included in our roadmap for 4.0.

**Comment by bluetom** [comment]
These options has been improved in the current organizer versions 3.11.7 and 4.2.
