### ISSUE TITLE
slot time don't update correctly

### ISSUE THREAD

**Issue by aegea1500** [academic-moodle-cooperation/moodle-mod_organizer#92]
When you program another slot at another time, update to the last time and you don't see the previous one.
if a student have one slot time at 09.02.2021 and have another slot at 10.02.2021 the teacher only view the last slot.
The version is 3.6.3 (moodle 3.6.10)

thanks a lot
Alex

**Comment by goggo24** [comment]
Could you explain for steps more in detail - where he/she can see only the last slot?
At the moment we don't support multiple registration, you can only allow a user to make a reappointment. Than I see both slots in the table under the current version (moodle 3.10).

Cheers, Eva

**Comment by aegea1500** [comment]
> 
> 
> Could you explain for steps more in detail - where he/she can see only the last slot?
> At the moment we don't support multiple registration, you can only allow a user to make a reappointment. Than I see both slots in the table under the current version (moodle 3.10).
> 
> Cheers, Eva

Hello Eva,

In version 3.9, when a student requests another reservation, only his last reservation remains.
A student may request two reservations on the same day at different times.

Cheers, Alex

**Comment by aegea1500** [comment]
In version 3.9, when a student requests another reservation, only his last reservation remains.
A student may request two reservations on the same day at different times.

Cheers, Alex

**Comment by bluetom** [comment]
With the current organizer versions 4.2 and 3.11.7 the multibooking feature has been introduced. Now students can book more than one slot (in the usual way).
