### ISSUE TITLE
Table alignment is not correct for group organizer

### ISSUE THREAD

**Issue by iamsuperwoman81** [academic-moodle-cooperation/moodle-mod_organizer#93]
After I have created the organizer for group, then create slot, then go to Registration Status Tab. 
Here you can see the Table alignment is not correct for group organizer after the Participants Column.

Please see the print screen in below.
![Clipboard02](https://user-images.githubusercontent.com/25074507/110564045-2e29ee00-8187-11eb-9dee-5f3bcdf35503.jpg)

**Comment by goggo24** [comment]
Thanks for reporting. I just tried to reproduce it under Moodle 3.10 - but there it looks okay. Which organizer version do you use?
<img width="442" alt="table_organizer" src="https://user-images.githubusercontent.com/16721900/113831278-b94ad380-9787-11eb-82ef-4481f748e080.png">

**Comment by iamsuperwoman81** [comment]
Hi! I'm using version 3.4.3 which is for Moodle 3.4

**Comment by goggo24** [comment]
Bug fixes for general Moodle core bugs in 3.4.x ended 12 November 2018 (12 months) - we use the same rhythm, so I close this issue.
