### ISSUE TITLE
 Issues highlighted by admin/cli/check_database_schema.php

### ISSUE THREAD

**Issue by abias** [academic-moodle-cooperation/moodle-mod_organizer#98]
Every now and then, we are running the admin/cli/check_database_schema.php script in our Moodle installation.

This time, these issues were highlighted:

```
-------------------------------------------------------------------------------
organizer
 * column 'visibility' should allow NULL (I)
 * column 'visibility' has default '0', expected '1' (I)
-------------------------------------------------------------------------------
organizer_slots
 * column 'duration' should be NOT NULL (I)
 * column 'visibility' should allow NULL (I)
 * column 'isanonymous' is not expected (I)
-------------------------------------------------------------------------------
```

As https://github.com/academic-moodle-cooperation/moodle-mod_organizer/blob/master/db/upgrade.php is quite long and complicated and as we are using the plugin for some time now, I did not look for immediate discrepancies between https://github.com/academic-moodle-cooperation/moodle-mod_organizer/blob/master/db/install.xml and https://github.com/academic-moodle-cooperation/moodle-mod_organizer/blob/master/db/upgrade.php which might have caused this issue.

May I ask you for your kind feedback about these reported issues? Should I just fix them locally in our database or is this something which could also affect other Moodle instances and should be fixed with an additional step in upgrade.php?

Thanks in advance,
Alex

**Comment by goggo24** [comment]
included in v.3.11.2 - thanks for reporting.
